title: CS236G Generative Adversarial Networks (GANs)
baseurl: "https://cs236g.stanford.edu"
repository: "CS236G"

# Theme settings
doks:
    color_theme: blue
    header:
        logo:
            text: CS236G
            image: true
        nav:
            - item_name: Syllabus
              item_url: '/syllabus'
            - item_name: Office Hours
              item_url: '/officehours'
            - item_name: Project
              item_url: '/project'
            - item_name: Memes
              item_url: '/memes'
            - item_name: FAQ
              item_url: '/faq'
    footer:
        content:
            logo:
                text:
                image:
            copyright: Copyright &copy; 2021. - Stanford University <br>All rights reserved.
    google_analytics: UA-180658495-1
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'scripts']
permalink: /:title/

# Course logistics
course:
    quarter: 2020-21 Winter
    time: T/Th 2:30 PM - 3:20 PM
    venue: '<a href="https://stanford.zoom.us/j/95821612145?pwd=dXVXd0hTdjBacTB6N0kwcG1RSkR4dz09">Zoom</a>'
    piazza: &pz 'http://piazza.com/stanford/winter2021/cs236g'
    queuestatus:
        url: &qs 'https://queuestatus.com/queues/1147'
        name: 'CS236G (2020-21 Winter)'
    canvas: 'https://canvas.stanford.edu'
    qa: &qa 'cs236g@cs.stanford.edu'
    midterm_time: ''
    project_timeline:
        proposal: 2020-09-30T23:59:00-07:00
        milestone: 2020-10-30T23:59:00-07:00
        poster_and_report: 2020-11-17T9:50:00-07:00
        long_date_format: "%B %-d, %A %I:%M %p"
        syllabus_date_format: "%m/%d %A %I:%M %p"
    links:
        syllabus:
            icon:
            content: Syllabus
            url: '/syllabus'
            external_url: false
        piazza:
            icon:
            content: Piazza
            url: *pz
            external_url: true
        video:
            icon:
            content: Lecture videos (Canvas)
            url: 'https://stanford-pilot.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx#folderID=%22d76ed749-1aaa-4fba-9c50-ac8b010eb6af%22'
            external_url: true
        queuestatus:
            icon:
            content: QueueStatus
            url: *qs
            external_url: true
        project_appt_calendly:
            content: Meet with Project TA
            url: '/officehours/#table'
            external_url: false
        google_cal:
            icon:
            content: Calendar
            url: '/officehours/#calendar'
            external_url: false
        submit_memes:
            icon:
            content: Submit memes
            url: 'https://forms.gle/AMpCSs5DB6GWx9QN6'
            external_url: true

    staff:
        - name: Sharon Zhou
          type: Instructor
          url: https://www.linkedin.com/in/zhousharon/
          image: sharon.png
          calendly: https://calendly.com/sharonz/cs236g-office-hours
          zoom_id: 91766994906
          zoom_link: https://stanford.zoom.us/s/91766994906?pwd=bG1mWnl6ZERXeHh3R2dzR2k3ZWJtQT09

    ta:
        - name: Gan Gogh
          type: TA
          url: https://artbreeder.com/
          image: gangogh.jpg
        - name: Eric Zelikman
          type: TA
          image: eric.png
          zoom_id: 2213214134
          zoom_link: https://stanford.zoom.us/j/2213214134?pwd=TjV4aTl5djhqcjRza3FNeVM3NDJXZz09
          calendly: https://calendly.com/ezelikman/oh
        - name: Hikaru Hotta
          type: TA
          image: hikaru.png
          zoom_id: 97045267696
          zoom_link: https://stanford.zoom.us/s/97045267696?pwd=MnNxck5VZzVWQldwZUV0OU9EUVo4UT09
          calendly: https://calendly.com/hikaru-hotta/15min
        - name: Silvia Gong
          type: TA
          image: silvia.png
          zoom_id: 96502819445
          zoom_link: https://stanford.zoom.us/j/96502819445?pwd=Sk5Vak9OSFduQkp1T2xtSERuYlY0QT09
          calendly: https://calendly.com/silvgong
        - name: Sofian Zalouk
          type: TA
          image: sofian.png
          zoom_id: 91078117842
          zoom_link: https://stanford.zoom.us/j/91078117842?pwd=dWlsRC9uOU9OczZBejlPTnFSZWd2dz09
          calendly: https://calendly.com/szalouk/sofian-office-hours
        - name: Vincent Liu
          type: TA
          image: vincent.png
          zoom_id: 97931205842
          zoom_link: https://stanford.zoom.us/s/97931205842?pwd=ZDhnMkcvVmRaMHZIL0JGRGhrSGZMZz09
          calendly: https://calendly.com/vliu15/cs-236g-office-hours
        - name: William Zhuk
          type: TA
          image: william.png
          calendly: https://calendly.com/willzhuk/15min
          zoom_id: 94672223884
          zoom_link: https://stanford.zoom.us/j/94672223884?pwd=QXYwb3hQSVBSaDMyL0VYMHhaZXlGdz09

    project_mentor:
        - name: Claire Pajot
          type: Mentor
          image: claire.png
          calendly: https://calendly.com/cpajot/cs236g-oh
          zoom_id: 98386728001
          zoom_link: https://stanford.zoom.us/j/98386728001?pwd=UWtJL1RjMmpMNUJEbTZaQ2RRTHMzQT09
        - name: Louis Blankemeier
          type: Mentor
          image: louis.png
          calendly: https://calendly.com/lblankem/louis-blankemeier-s-cs236g-office-hours
          zoom_id: 96530342314
          zoom_link: https://stanford.zoom.us/j/96530342314?pwd=Z2w2TThQV3hKdWM5K0p0SWJsUTNYQT09
        - name: Tim Gianitsos
          type: Mentor
          image: tim.png
          calendly: https://calendly.com/tgianit/cs236g-office-hours
          zoom_id: 93076843389
          zoom_link: https://stanford.zoom.us/j/93076843389?pwd=bDcxRTR2UnhQeFhXQTA5MVkrRGM1dz09
